apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-back
spec:
  selector:
    matchLabels:
      app: api-back
  template:
    metadata:
      labels:
        app: api-back
    spec:
      containers:
      - name: api-back
        image: rcregistry.azurecr.io/api-back:1
        ports:
        - containerPort: 8000
