apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-back
  labels:
    app: api-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-back
  template:
    metadata:
      labels:
        app: api-back
    spec:
      containers:
      - name: api-back
        image: rcregistry.azurecr.io/api-back:2
        imagePullPolicy: Always
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
        livenessProbe:
          exec:
            command:
            - cat
            - main.py
          initialDelaySeconds: 5
          periodSeconds: 5